import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const SinglePostPage: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center">
        <div>
          Post View
          <p>
            <strong>{id}</strong>
          </p>
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
